config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

RedmineApp::Application.routes.draw do
    match '/doc/preview', :controller => 'previews', :action => 'doc', :as => 'preview_documents', :via => [:get, :post, :put]
end

app/views/documents/_document.html.erb
<h4><%= link_to h(document.title), document_path(document) %></h4>
<p><em><%= format_time(document.updated_on) %></em></p>
<hr>

<!-- <div class="wiki"> -->
  <%#= textilizable(truncate_lines(document.description), :object => document) %>
<!-- </div> -->

app/views/documents/edit.html.erb
<h2><%=l(:label_document)%></h2>

<%= labelled_form_for @document, :html => {:id=>'document-form'} do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <p>
    <%= submit_tag l(:button_save) %>
    <%= preview_link preview_documents_path(:project_id => @project), 'document-form' %>
  </p>
<% end %>
<div id="preview" class="wiki"></div>

app/views/documents/index.html.erb
<div class="contextual">
<%= link_to l(:label_document_new), new_project_document_path(@project), :class => 'icon icon-add',
      :onclick => 'showAndScrollTo("add-document", "document_title"); return false;' if User.current.allowed_to?(:add_documents, @project) %>
</div>

<div id="add-document" style="display:none;">
<h2><%=l(:label_document_new)%></h2>
<%= labelled_form_for @document, :url => project_documents_path(@project), :html => {:multipart => true, :id=>'new-document-form'} do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<p>
  <%= submit_tag l(:button_create) %>
  <%= link_to l(:button_cancel), "#", :onclick => '$("#add-document").hide(); return false;' %>
  | 
  <%= preview_link preview_documents_path(:project_id => @project), 'new-document-form' %>
</p>
<% end %>
<div id="preview" class="wiki"></div>
</div>

<h2><%=l(:label_document_plural)%></h2>

<% if @grouped.empty? %><p class="nodata"><%= l(:label_no_data) %></p><% end %>

<% @grouped.keys.sort.each do |group| %>
    <h3><%= group %></h3>
    <%= render :partial => 'documents/document', :collection => @grouped[group] %>
<% end %>

<% content_for :sidebar do %>
  <h3><%= l(:label_sort_by, '') %></h3>
  <ul>
    <li><%= link_to(l(:field_category), {:sort_by => 'category'},
                    :class => (@sort_by == 'category' ? 'selected' :nil)) %></li>
    <li><%= link_to(l(:label_date), {:sort_by => 'date'},
                    :class => (@sort_by == 'date' ? 'selected' :nil)) %></li>
    <li><%= link_to(l(:field_title), {:sort_by => 'title'},
                    :class => (@sort_by == 'title' ? 'selected' :nil)) %></li>
    <li><%= link_to(l(:field_author), {:sort_by => 'author'},
                    :class => (@sort_by == 'author' ? 'selected' :nil)) %></li>
  </ul>
<% end %>

<% html_title(l(:label_document_plural)) -%>

app/views/issues/_attributes.html.erb
<%= labelled_fields_for :issue, @issue do |f| %>

<div class="splitcontent">
<div class="splitcontentleft">
<% if @issue.safe_attribute?('status_id') && @allowed_statuses.present? %>
<p><%= f.select :status_id, (@allowed_statuses.collect {|p| [p.name, p.id]}), {:required => true},
                :onchange => "updateIssueFrom('#{escape_javascript project_issue_form_path(@project, :id => @issue, :format => 'js')}')" %></p>

<% else %>
<p><label><%= l(:field_status) %></label> <%= h(@issue.status.name) %></p>
<% end %>

<% if @issue.safe_attribute? 'priority_id' %>
<p><%= f.select :priority_id, (@priorities.collect {|p| [p.name, p.id]}), {:required => true}, :disabled => !@issue.leaf? %></p>
<% end %>

<% if @issue.safe_attribute? 'assigned_to_id' %>
<p><%= f.select :assigned_to_id, principals_options_for_select(@issue.assignable_users, @issue.assigned_to), :include_blank => true, :required => @issue.required_attribute?('assigned_to_id') %></p>
<% end %>

<% if @issue.safe_attribute?('category_id') && @issue.project.issue_categories.any? %>
<p><%= f.select :category_id, (@issue.project.issue_categories.collect {|c| [c.name, c.id]}), :include_blank => true, :required => @issue.required_attribute?('category_id') %>
<%= link_to(image_tag('add.png', :style => 'vertical-align: middle;'),
            new_project_issue_category_path(@issue.project),
            :remote => true,
            :method => 'get',
            :title => l(:label_issue_category_new),
            :tabindex => 200) if User.current.allowed_to?(:manage_categories, @issue.project) %></p>
<% end %>

<% (@issue.new_record? || @issue.parent_issue_id) && if @issue.safe_attribute?('grorder') %>
    <p><%= f.text_field :grorder, :size => 4, :required => @issue.required_attribute?('grorder') %></p>
<% end %>

<% if @issue.safe_attribute?('fixed_version_id') && @issue.assignable_versions.any? %>
<p><%= f.select :fixed_version_id, version_options_for_select(@issue.assignable_versions, @issue.fixed_version), :include_blank => true, :required => @issue.required_attribute?('fixed_version_id') %>
<%= link_to(image_tag('add.png', :style => 'vertical-align: middle;'),
            new_project_version_path(@issue.project),
            :remote => true,
            :method => 'get',
            :title => l(:label_version_new),
            :tabindex => 200) if User.current.allowed_to?(:manage_versions, @issue.project) %>
</p>
<% end %>
</div>

<div class="splitcontentright">
<% if @issue.safe_attribute? 'parent_issue_id' %>
<p id="parent_issue"><%= f.text_field :parent_issue_id, :size => 10, :required => @issue.required_attribute?('parent_issue_id') %></p>
<%= javascript_tag "observeAutocompleteField('issue_parent_issue_id', '#{escape_javascript auto_complete_issues_path(:project_id => @issue.project, :scope => Setting.cross_project_subtasks)}')" %>
<% end %>

<% if @issue.safe_attribute? 'start_date' %>
<p id="start_date_area">
  <%= f.text_field(:start_date, :size => 10, :disabled => !@issue.leaf?,
                   :required => @issue.required_attribute?('start_date')) %>
  <%= calendar_for('issue_start_date') if @issue.leaf? %>
</p>
<% end %>

<% if @issue.safe_attribute? 'due_date' %>
<p id="due_date_area">
  <%= f.text_field(:due_date, :size => 10, :disabled => !@issue.leaf?,
                   :required => @issue.required_attribute?('due_date')) %>
  <%= calendar_for('issue_due_date') if @issue.leaf? %>
</p>
<% end %>

<% if @issue.safe_attribute? 'estimated_hours' %>
<p><%= f.text_field :estimated_hours, :size => 3, :disabled => !@issue.leaf?, :required => @issue.required_attribute?('estimated_hours') %> <%= l(:field_hours) %></p>
<% end %>

<% if @issue.safe_attribute?('done_ratio') && @issue.leaf? && Issue.use_field_for_done_ratio? %>
<p><%= f.select :done_ratio, ((0..10).to_a.collect {|r| ["#{r*10} %", r*10] }), :required => @issue.required_attribute?('done_ratio') %></p>
<% end %>
</div>
</div>

<% if @issue.safe_attribute? 'custom_field_values' %>
<%= render :partial => 'issues/form_custom_fields' %>
<% end %>

<% end %>

<% include_calendar_headers_tags %>

app/views/issues/_form.html.erb
<%= labelled_fields_for :issue, @issue do |f| %>
<%= call_hook(:view_issues_form_details_top, { :issue => @issue, :form => f }) %>

<% if @issue.safe_attribute? 'is_private' %>
<p style="float:right; margin-right:1em;">
  <%= f.check_box :is_private, :no_label => true %><label class="inline" for="issue_is_private" id="issue_is_private_label"><%= l(:field_is_private) %></label>
</p>
<% end %>

<% if @issue.safe_attribute? 'project_id' %>
<p><%= f.select :project_id, project_tree_options_for_select(@issue.allowed_target_projects, :selected => @issue.project), {:required => true},
                :onchange => "updateIssueFrom('#{escape_javascript project_issue_form_path(@project, :id => @issue, :format => 'js')}')" %></p>
<% end %>

<% if @issue.safe_attribute? 'tracker_id' %>
<p><%= f.select :tracker_id, @issue.project.trackers.collect {|t| [t.name, t.id]}, {:required => true},
                :onchange => "updateIssueFrom('#{escape_javascript project_issue_form_path(@project, :id => @issue, :format => 'js')}')" %></p>
<% end %>

<% if @issue.safe_attribute? 'subject' %>
<p><%= f.text_field :subject, :size => 80, :maxlength => 255, :required => true %></p>
<% end %>

<% if @issue.safe_attribute? 'description' %>
<p>
  <%= f.label_for_field :description, :required => @issue.required_attribute?('description') %>
  <%= link_to_function image_tag('edit.png'), '$(this).hide(); $("#issue_description_and_toolbar").show()' unless @issue.new_record? %>
  <%= content_tag 'span', :id => "issue_description_and_toolbar", :style => (@issue.new_record? ? nil : 'display:none') do %>
    <%= f.text_area :description,
                   :cols => 60,
                   :rows => (@issue.description.blank? ? 10 : [[10, @issue.description.length / 50].max, 100].min),
                   :accesskey => accesskey(:edit),
                   :class => 'wiki-edit',
                   :no_label => true %>
  <% end %>
</p>
<%= wikitoolbar_for 'issue_description' %>
<% end %>

<div id="attributes" class="attributes">
  <%= render :partial => 'issues/attributes' %>
</div>

<%= call_hook(:view_issues_form_details_bottom, { :issue => @issue, :form => f }) %>
<% end %>

<% heads_for_wiki_formatter %>

<%= javascript_tag do %>
$(document).ready(function(){
  $("#issue_tracker_id, #issue_status_id").each(function(){
    $(this).val($(this).find("option[selected=selected]").val());
  });
});
<% end %>

app/views/issues/_relations.html.erb
<div class="contextual">
<% if User.current.allowed_to?(:manage_issue_relations, @project) %>
  <%= toggle_link l(:button_add), 'new-relation-form', {:focus => 'relation_issue_to_id'} %>
<% end %>
</div>

<p><strong><%=l(:label_related_issues)%></strong></p>

<% if @relations.present? %>
<form>
<table class="list issues">
<% reset_cycle %>
<% @relations.each do |relation| %>
  <% other_issue = relation.other_issue(@issue) -%>

  <tr class="issue hascontextmenu <%= cycle('odd', 'even') %> <%=other_issue.css_classes%>" id="relation-<%= relation.id %>">
  <td class="checkbox"><%= check_box_tag("ids[]", other_issue.id, false, :id => nil) %></td>
  <td><%= other_issue.visible_custom_field_values[3] %></td>
  <td><%= other_issue.fixed_version %></td>
  <td class="subject">
    <%= l(relation.label_for(@issue)) %>
    <%= "(#{l('datetime.distance_in_words.x_days', :count => relation.delay)})" if relation.delay && relation.delay != 0 %>
    <%= h(other_issue.project) + ' - ' if Setting.cross_project_issue_relations? %>
    <%= link_to_issue(other_issue, :truncate => 60) %>
  </td>
  <td class="status"><%=h other_issue.status.name %></td>
  <td class="start_date"><%= format_date(other_issue.start_date) %></td>
  <td class="due_date"><%= format_date(other_issue.due_date) %></td>
  <td class="buttons"><%= link_to image_tag('link_break.png'),
                                  relation_path(relation),
                                  :remote => true,
                                  :method => :delete,
                                  :data => {:confirm => l(:text_are_you_sure)},
                                  :title => l(:label_relation_delete) if User.current.allowed_to?(:manage_issue_relations, @project) %></td>
  </tr>
<% end %>
</table>
</form>
<% end %>

<%= form_for @relation, {
                 :as => :relation, :remote => true,
                 :url => issue_relations_path(@issue),
                 :method => :post,
                 :html => {:id => 'new-relation-form', :style => 'display: none;'}
               } do |f| %>
<%= render :partial => 'issue_relations/form', :locals => {:f => f}%>
<% end %>

app/views/issues/show.html.erb
<%= render :partial => 'action_menu' %>

<h2><%= issue_heading(@issue) %></h2>

<div class="<%= @issue.css_classes %> details">
  <% if @prev_issue_id || @next_issue_id %>
    <div class="next-prev-links contextual">
      <%= link_to_if @prev_issue_id,
                     "\xc2\xab #{l(:label_previous)}",
                     (@prev_issue_id ? issue_path(@prev_issue_id) : nil),
                     :title => "##{@prev_issue_id}" %> |
      <% if @issue_position && @issue_count %>
        <span class="position"><%= l(:label_item_position, :position => @issue_position, :count => @issue_count) %></span> |
      <% end %>
      <%= link_to_if @next_issue_id,
                     "#{l(:label_next)} \xc2\xbb",
                     (@next_issue_id ? issue_path(@next_issue_id) : nil),
                     :title => "##{@next_issue_id}" %>
    </div>
  <% end %>

  <%= avatar(@issue.author, :size => "50") %>

<div class="subject">
<%= render_issue_subject_with_tree(@issue) %>
</div>
        <p class="author">
        <%= authoring @issue.created_on, @issue.author %>.
        <% if @issue.created_on != @issue.updated_on %>
        <%= l(:label_updated_time, time_tag(@issue.updated_on)).html_safe %>.
        <% end %>
        </p>


<table class="attributes">
<%= issue_fields_rows do |rows|
  rows.left l(:field_status), h(@issue.status.name), :class => 'status'
  rows.left l(:field_priority), h(@issue.priority.name), :class => 'priority'

  unless @issue.disabled_core_fields.include?('assigned_to_id')
    rows.left l(:field_assigned_to), avatar(@issue.assigned_to, :size => "14").to_s.html_safe + (@issue.assigned_to ? link_to_user(@issue.assigned_to) : "-"), :class => 'assigned-to'
  end
  unless @issue.disabled_core_fields.include?('category_id')
    rows.left l(:field_category), h(@issue.category ? @issue.category.name : "-"), :class => 'category'
  end
  unless @issue.disabled_core_fields.include?('fixed_version_id')
    rows.left l(:field_fixed_version), (@issue.fixed_version ? link_to_version(@issue.fixed_version) : "-"), :class => 'fixed-version'
  end

  unless @issue.disabled_core_fields.include?('start_date')
    rows.right l(:field_start_date), format_date(@issue.start_date), :class => 'start-date'
  end
  unless @issue.disabled_core_fields.include?('due_date')
    rows.right l(:field_due_date), format_date(@issue.due_date), :class => 'due-date'
  end
  unless @issue.disabled_core_fields.include?('done_ratio')
    rows.right l(:field_done_ratio), progress_bar(@issue.done_ratio, :width => '80px', :legend => "#{@issue.done_ratio}%"), :class => 'progress'
  end
  unless @issue.disabled_core_fields.include?('estimated_hours')
    unless @issue.estimated_hours.nil?
      rows.right l(:field_estimated_hours), l_hours(@issue.estimated_hours), :class => 'estimated-hours'
    end
  end
  if (@issue.parent_issue_id)
    rows.right l(:field_grorder), h(@issue.grorder), :class => 'grorder'
  end
  if User.current.allowed_to?(:view_time_entries, @project)
    rows.right l(:label_spent_time), (@issue.total_spent_hours > 0 ? link_to(l_hours(@issue.total_spent_hours), issue_time_entries_path(@issue)) : "-"), :class => 'spent-time'
  end
end %>
<%= render_custom_fields_rows(@issue) %>
<%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
</table>

<% if @issue.description? || @issue.attachments.any? -%>
<hr />
<% if @issue.description? %>
<div class="description">
  <div class="contextual">
  <%= link_to l(:button_quote), quoted_issue_path(@issue), :remote => true, :method => 'post', :class => 'icon icon-comment' if authorize_for('issues', 'edit') %>
  </div>

  <p><strong><%=l(:field_description)%></strong></p>
  <div class="wiki">
  <%= textilizable @issue, :description, :attachments => @issue.attachments %>
  </div>
</div>
<% end %>
<%= link_to_attachments @issue, :thumbnails => true %>
<% end -%>

<%= call_hook(:view_issues_show_description_bottom, :issue => @issue) %>

<% if !@issue.leaf? || User.current.allowed_to?(:manage_subtasks, @project) %>
<hr />
<div id="issue_tree">
<div class="contextual">
  <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
</div>
<p><strong><%=l(:label_subtask_plural)%></strong></p>
<%= render_descendants_tree(@issue) unless @issue.leaf? %>
</div>
<% end %>

<% if @relations.present? || User.current.allowed_to?(:manage_issue_relations, @project) %>
<hr />
<div id="relations">
<%= render :partial => 'relations' %>
</div>
<% end %>

</div>

<% if @changesets.present? %>
<div id="issue-changesets">
<h3><%=l(:label_associated_revisions)%></h3>
<%= render :partial => 'changesets', :locals => { :changesets => @changesets} %>
</div>
<% end %>

<% if @journals.present? %>
<div id="history">
<h3><%=l(:label_history)%></h3>
<%= render :partial => 'history', :locals => { :issue => @issue, :journals => @journals } %>
</div>
<% end %>


<div style="clear: both;"></div>
<%= render :partial => 'action_menu' %>

<div style="clear: both;"></div>
<% if @issue.editable? %>
  <div id="update" style="display:none;">
  <h3><%= l(:button_edit) %></h3>
  <%= render :partial => 'edit' %>
  </div>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
  <%= f.link_to 'PDF' %>
<% end %>

<% html_title "#{@issue.tracker.name} ##{@issue.id}: #{@issue.subject}" %>

<% content_for :sidebar do %>
  <%= render :partial => 'issues/sidebar' %>

  <% if User.current.allowed_to?(:add_issue_watchers, @project) ||
    (@issue.watchers.present? && User.current.allowed_to?(:view_issue_watchers, @project)) %>
    <div id="watchers">
      <%= render :partial => 'watchers/watchers', :locals => {:watched => @issue} %>
    </div>
  <% end %>
<% end %>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, {:format => 'atom', :key => User.current.rss_key}, :title => "#{@issue.project} - #{@issue.tracker} ##{@issue.id}: #{@issue.subject}") %>
<% end %>

<%= context_menu issues_context_menu_path %>

app/views/versions/_table_of_issues.html.erb
<%
hide_table ||= false
curr_block_statueses = Hash.new 
curr_block_statueses_count = Hash.new 
issues.each do |issue|
    curr_block_statueses[issue.status.id] = issue.status 
    curr_block_statueses_count[issue.status.id] ||= 0 
    curr_block_statueses_count[issue.status.id] += 1 
end 

# versions_last_status=0
# versions_status_count=0
# versions_status_count_all=0


%>
<% if hide_table %>
<button class="toggle_versions_table" onclick="roadmap.hideTable(this);" versionid="<%=version.id%>" title="Сворачивает все задачи текущей версии">свернуть список задач</button>
<br>
<% end %>

<% if hide_table %>
<div class="versions_table" versionid="<%=version.id%>">
<% end %>

<div>
    
    <span class="hide_version_status">Спрятать</span>/<span class="show_version_status">Показать</span> статусы (<a class="toggle_versions_allstatus show_version_status" onclick="roadmap.toggleAllStatus(this);" versionid="<%=version.id%>" title="Скрыть/Показать все задачи не зависимо от статуса">все</a>): | 
    <%
    curr_block_statueses.each do |issueid, issuestat| %>
      <a class="toggle_versions_status show_version_status" onclick="roadmap.toggleByStatus(this);" versionid="<%=version.id%>" statusid="<%=issuestat.id%>" statusname="<%=issuestat.name%>" title="Скрыть/Показать только те задачи которые соответсвуют текущему статусу"><%=issuestat.name%>&nbsp;(<%=curr_block_statueses_count[issuestat.id]%>)</a>&nbsp;| 
    <% end %>
    <br>
</div>

<%= form_tag({}) do -%>
    <table class="<%=table_options[:class]%>">
        <caption><%= table_options[:caption] %></caption>

        <thead>
            <tr>
                <th class="checkbox hide-when-print" style="display: none;"></th>
                <th>#</th>
                <th>Трекер</th>
                <th>Статус</th>
                <th></th>
                <th>Назначена</th>
                <th>Тема</th>
            </tr>
        </thead>

        <tbody>

        <% curr_block_statueses.each do |statusid, statusitem| %>
            <tr class="versions_total_statuses_message" versionid="<%=version.id%>"  statusid="<%=statusid%>">
                <td colspan="6" style="text-align: left">
                    скрыто записей: <%=curr_block_statueses_count[statusid]%>;  со статусом: <%=statusitem.name%>;
                </td>
            </tr>
        <% end %>

        <% issue_list(issues) do |issue, level| -%>

            <% cssclass = '' %>
            <% cssclass <<  " issue idnt idnt-#{level} " if level > 0 %>



            <tr class=" <%=cssclass%> issues_stat <%=table_options[:tbody][:tr_class]%>" versionid="<%=version.id%>" statusid="<%=issue.status.id%>" >
                <td class="checkbox"><%= check_box_tag 'ids[]', issue.id, false, :id => nil %></td>
                <td style="text-align: left;"><%= link_to("##{issue.id}", issue_path(issue), :target=>'_blank')%></td>
                <td style="text-align: left;"><%=issue.tracker%></td>
                <td style="text-align: left;"><%=issue.status%></td>
                <td style="text-align: left;">
                    <%=issue.grorder%>
                </td>
                <td style="text-align: left;"><%=issue.assigned_to%></td>
                <td class="subject"><%= link_to(issue.subject.truncate(60), issue_path(issue), :target=>'_blank') %></td>
            </tr>


        <% end -%>
        </tbody>


    </table>
<% end %>

<% if hide_table %>
</div> <!-- class=versions_table-->
<% end %>

app/views/versions/index.html.erb
<div class="contextual">
  <%= link_to(l(:label_version_new), new_project_version_path(@project),
              :class => 'icon icon-add') if User.current.allowed_to?(:manage_versions, @project) %>
</div>

<h2><%=l(:label_roadmap)%></h2>
<div style="display: hidden;" id="current_project" project-id="<%=@project.id%>" project-name="<%=@project.name%>"></div>
<div style="margin-bottom: 50px;">
	<button style="float: right;" onclick="roadmap.clearall()" title="Очистить все сохраненные состояния!">Очистисть состояния!</button>
</div>
<% if @versions.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <div id="roadmap">
  <% @versions.each do |version| %>
    <div style="border:1px dashed black; border: 1px solid #ddd;
  padding: 0px 8px;
  margin: 12px -13px;
  background: rgb(252, 252, 252);
  border-radius: 4px;">
        <h3 class="version"><%= link_to_version version, :name => version_anchor(version) %></h3>
        <%= render :partial => 'versions/overview', :locals => {:version => version} %>
        <%= render(:partial => "wiki/content",
                   :locals => {:content => version.wiki_page.content}) if version.wiki_page %>
        <% if (issues = @issues_by_version[version]) && issues.size > 0 %>
            <%= render(:partial => 'versions/table_of_issues', :locals => { 
                    :issues => issues, :version => version, :hide_table => true, :table_options => { :tbody => { :tr_class=>'hascontextmenu' }, :class => 'list related-issues', :caption => l(:label_related_issues) } }) %>
        <% end %>
        <%= call_hook :view_projects_roadmap_version_bottom, :version => version %>
    </div>
  <% end %>
  </div>
<% end %>

<% content_for :sidebar do %>
<%= form_tag({}, :method => :get) do %>
<h3><%= l(:label_roadmap) %></h3>
<ul>
<% @trackers.each do |tracker| %>
  <li>
    <label>
      <%= check_box_tag("tracker_ids[]", tracker.id,
                        (@selected_tracker_ids.include? tracker.id.to_s),
                        :id => nil) %>
      <%= tracker.name %>
    </label>
  </li>
<% end %>
</ul>
<p></p>
<ul>
  <li>
    <label for="completed">
      <%= check_box_tag "completed", 1, params[:completed] %> <%= l(:label_show_completed_versions) %>
    </label>
  </li>
  <% if @project.descendants.active.any? %>
  <li>
    <%= hidden_field_tag 'with_subprojects', 0 %>
    <label>
      <%= check_box_tag 'with_subprojects', 1, @with_subprojects %> <%=l(:label_subproject_plural)%>
    </label>
  </li>
  <% end %>
</ul>
<p><%= submit_tag l(:button_apply), :class => 'button-small', :name => nil %></p>
<% end %>

<h3><%= l(:label_version_plural) %></h3>
<ul>
<% @versions.each do |version| %>
  <li>
    <%= link_to(format_version_name(version), "##{version_anchor(version)}") %>
  </li>
<% end %>
</ul>
<% if @completed_versions.present? %>
<p>
  <%= link_to_function l(:label_completed_versions), 
                       '$("#toggle-completed-versions").toggleClass("collapsed"); $("#completed-versions").toggle()',
                       :id => 'toggle-completed-versions', :class => 'collapsible collapsed' %>
  <ul id = "completed-versions" style = "display:none;">
    <% @completed_versions.each do |version| %>
      <li><%= link_to(format_version_name(version), version_path(version)) %></li>
    <% end %>  
  </ul>
</p>
<% end %>
<% end %>

<% html_title(l(:label_roadmap)) %>

<%= context_menu issues_context_menu_path %>


<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'usability', :plugin => 'redmine_usability' %>
    <%= javascript_include_tag 'js_cookie', :plugin => 'redmine_usability' %>
    <%= javascript_include_tag 'self_lib', :plugin => 'redmine_usability' %>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            console.log('run versions -> index.html.erb');
            roadmap.init();
        });
    </script>
<% end %>